In [ ]:
# plot gameboard
#loop over even and odd numbers to check player turns
#ask for an input for where you want the token
#check if the input is a legal move
#plot the arrayboard on the gameboard
#check if there is 4 in a row after the input, and then if the board is full, if not next player turn

import numpy as np
from matplotlib import pyplot as plt

def playerturn(i,graphicboard):
    arrayboard=np.zeros([6,7])
    wincondition=4                       #need to make this an input for the user to choose how many to connect 2
    gamewon=False                         #also have them choose board size
    while gamewon==False:
        if i%2==0:            #if the number is even
            playerone=True
            playermove=move(playerone,arrayboard,wincondition)   #asks the player to input move
            arrayboard=plotmove(playermove,playerone,arrayboard)
            #graphicalboard(playermove,arrayboard,playerone,graphicboard)
            gamewon=gamewin(arrayboard,wincondition,playermove)
            print("gamewon is","",gamewon)
            i=i+1
        else:
            playerone=False
            playermove=move(playerone,arrayboard,wincondition)   #asks the player to input move
            arrayboard=plotmove(playermove,playerone,arrayboard)
            #graphicalboard(playermove,arrayboard,playerone,board)
            gamewon=gamewin(arrayboard,wincondition,playermove)
            print("gamewon is","",gamewon)                  
            i=i+1
    if gamewon ==True:
        print("waheywewoon")
            
            
def plotmove(move,playerone,arrayboard):
    if playerone==True:
        print(move)
        arrayboard[move[0],move[1]]=1
        print(arrayboard)
        return(arrayboard)
    else:
        arrayboard[move[0],move[1]]=2
        print(arrayboard)
        return(arrayboard)

        

def graphicalboard(move,arrayboard,playerone,board):
    ymove=(move[0]+1-move[0])    #converts it into graph co-ordinates
    xmove=(move[1]+1)
    if playerone==True:
        board=plt.plot(xmove,ymove,'ro')
        print("ayo")
    else:
        board=plt.plot(xmove,ymove,'bo')
        print("ayo2")
    plt.show(board)
        
        
def move(playeroneturn,arrayboard,wincondition):
    failstate=False
    if playeroneturn == True: #checks to see which players turn it is
        p=("Player One, ")
    else:
        p=("Player Two, ")
    while True: #takes the input and checks if its legal, and then passes to the plot function
        print()        
        print(p)
        print()
        try:
            move=eval(input("Please enter the co-ordinates of where you would like your token in an x-y format: "))
        except:
            print("Please enter a legal move.")
            continue
        (correctmove,failstate)=check(move,arrayboard,wincondition) 
        if failstate==True:
            continue
        else:
            return(correctmove)


            
def check(move,arrayboard,wincondition): #checks if the input is within the bounds of the board, if its a tuple, if its a legal connect 4 move etc.
    if type(move)==tuple and len(move)==2 and move[0]<=(arrayboard.shape[1]) and move[1]<=(arrayboard.shape[0]):
        failstate=False
        move=(np.array(move)-1)                         #minuses 1 because computer starts at 0
        move[[0,1]]=move[[1,0]]            #swaps variables so that coordinates are x,y instead of y,x
        for i in range(arrayboard.shape[0]):           #switches to the coordinate system that i want
            if move[0]==i:                             #loops to see what the move is and mirrors in x axis 
                move[0]=(arrayboard.shape[0]-i)-1
                break
            else:
                continue
        a=arrayboard[(move[0]),move[1]]           #it doesnt like if this is the if comparison without the variable
        if a!=0:                                #checks if there is a token where the move is
            print("Please move where there is no token.")
            failstate=True                
            return(move,failstate)

        if move[0]<0 or move[1]<0:                                #checks if there is a token where the move is
            print("Please enter a legal move.")
            failstate=True                
            return(move,failstate)
        (move,failstate)=legalmove(move,arrayboard,failstate)              
        if failstate == True:
            return(move,failstate)
        
        failstate=False
        return(move,failstate)
        
    else:
        print("Please enter a legal move.")
        failstate=True              
        return(move,failstate)
 

def gamewin(arrayboard,wincondition,playermove):
    x1=0         #x is rows, y is columns, xy is diagonals, numbers denote which player its being counted for
    x2=0        #e.g. if x2 reaches 4 player two wins connect four for a row
    y1=0
    y2=0
    xy1=0
    xy2=0
    ysize=(arrayboard.shape[0]-1)       #it only needs to check 5 times because it checks the one in front
    xsize=(arrayboard.shape[1]-1)       #it only needs to check 6 times because it checks the one in front
    for j in range(xsize):
        for i in range(xsize-1):                             #checks columns, -1 because it starts at 0, 0 to 4 is 5
            if arrayboard[i][0]==arrayboard[i+1][0]==1: 
                x1=x1+1
                print(x1)
                if x1==3:
                    p1=True
                    gamewon=True
                    return(gamewon,p1)     #p1 = True means player1 won, false means p2 won
            else:
                x1=0
            if arrayboard[i][0]==arrayboard[i+1][0]==2: 
                x2=x2+1
                print(x2)
                if x2==3:
                    p1=False
                    gamewon=True
                    return(gamewon,p1)     
            else:
                x2=0
                
    for j in range(ysize):
        for i in range(xsize-1):                             #checks rows
            if arrayboard[0][i]==arrayboard[0][i+1]==1: 
                y1=y1+1
                print(y1)
                if y1==3:                  #3 counts of 2 being adjacent is connect 4
                    p1=True
                    gamewon=True
                    return(gamewon,p1)     
            else:
                y1=0
            if arrayboard[0][i+1]==arrayboard[0][i+1]==2: 
                y2=y2+1
                print(y2)
                if y2==3:
                    p1=False
                    gamewon=True
                    return(gamewon,p1)    
            else:
                y2=0
    for j in range(ysize):
        for i in range(ysize-1):                             #checks ascending diagonals
            if arrayboard[i][j]==arrayboard[i+1][j+1]==1:
                xy1=xy1+1
                if xy1==3:
                    p1=True
                    gamewon=True
                    return(gamewon,p1)
            if arrayboard[i][j]==arrayboard[i+1][j+1]==2:
                xy2=xy2+1
                if xy2==3:
                    p1=False
                    gamewon=True
                    return(gamewon,p1)
    for j in range(ysize,0,-1):
        for i in range(ysize-1):                             #checks descending diagonals
            if arrayboard[i][j]==arrayboard[i+1][j-1]==1:
                xy1=xy1+1
                if xy1==3:
                    p1=True
                    gamewon=True
                    return(gamewon,p1)
            if arrayboard[i][j]==arrayboard[i+1][j-1]==2:
                xy2=xy2+1
                if xy2==3:
                    p1=False
                    gamewon=True
                    return(gamewon,p1)
    gamewon=False
    return(gamewon)
    
    
def plottedmove(move,arrayboard):          
    move=(np.array(move)-1)              #minuses 1 because computer starts at 0
    for i in range(arrayboard.shape[0]):           #switches to the coordinate system that i want
        if move[0]==i:                             #loops to see what the move is and mirrors in x axis 
            move[0]=(arrayboard.shape[0]-i)-1
            break
        else:
            continue
    return(move)

def legalmove(move,arrayboard,failstate):
    "checks if its on the bottom row or there's one below it, if there is failstate is true and illegal move"
    failstate==False
    x=move[0]
    y=move[1]                        #again it doesnt like comparisons without a neat variable so  here i am
    if x==5:                         #1st row, coordinates are flipped and start at 0 
        failstate==False
        return(move,failstate)
    elif arrayboard[x+1,y]==0:      #plus instead of minus since coordinates are flipped such that 6 is below 5
        print("Please enter a legal move.")
        failstate=True                
        return(move,failstate)
    else:
        failstate==False
        return(move,failstate)


            

for i in range(6):
    x=np.arange(1,8)
    y=np.full(7,[i+1])
    board=plt.scatter(x,y,c='white',s=200,edgecolors='black')
i=0
playerturn(i,board)

#arrayboard=np.zeros([6,7]) 
#move=[1,1]
#playerone=True
#plotmove(move,playerone,arrayboard)


Player One, 

Please enter the co-ordinates of where you would like your token in an x-y format: 1,1
[5 0]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
gamewon is  False

Player Two, 

Please enter the co-ordinates of where you would like your token in an x-y format: 1,2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
gamewon is  False

Player One, 

Please enter the co-ordinates of where you would like your token in an x-y format: 2,1
[5 1]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0.]]
gamewon is  False

Player Two, 

Please enter the co-ordinates of where you would like your token in an x-y format: 2,2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.

In [ ]:
# import numpy as np

mmyes=np.arange(1,4)
print(mmyes)
if  mmyes[0]==mmyes[1]==2:
    print("welcome back sethbling here")
else:
    print("sugma")

In [4]:
b=6
bnegative=-6

for i in range(6,-1,-1):
    print(i)

6
5
4
3
2
1
0
